Repository mensatt/backend, pull requests merged in 2022-07, with the labels that each got.

#80 Update images query
  internal/db/sql/queries/occurrence.sql
  internal/db/sqlc/occurrence.sql.go
Labels: bug

#94 Let Gin handle HTTP response code
  internal/images/images.go
Labels: bug

#95 Correct endpoint path
  internal/images/images.go
Labels: bug, high priority

#99 remove SetReviewApproval mutation and fix updateReview mutation
  internal/db/sql/queries/review.sql
  internal/db/sqlc/review.sql.go
  internal/graphql/gqlgen.yml
  internal/graphql/gqlserver/generated.go
  internal/graphql/models/generated.go
  internal/graphql/resolvers/inputs.resolvers.go
  internal/graphql/resolvers/mutations.resolvers.go
  internal/graphql/scalars/nullbool.go
  internal/graphql/schema/inputs.graphql
  internal/graphql/schema/mutations.graphql
Labels: bug, enhancement

#91 Trust no proxy to deliver the correct ClientIp
  pkg/server/server.go
Labels: enhancement, low priority
